### ISSUE TITLE
Room comments

### ISSUE THREAD

**Issue by selimdoyranli** [RadKod/parolla#55]
Requirements:

- Recognized / unique player nickname (Related with #47)
- Room comment field
- Room comment list with pagination
- Room like & dislike field for popularity filtering

**Comment by erayaydin** [comment]
Maybe "play count per player" can be used as popularity.

Room comments should be approved before publishing. It's make harder to manage project. I think, we can skip this feature for now.

**Comment by selimdoyranli** [comment]
> Maybe "play count per player" can be used as popularity.
> 
> Room comments should be approved before publishing. It's make harder to manage project. I think, we can skip this feature for now.

we don't need to moderate comments, we don't have to approve them. because moderation is not correct for comment list. users take action so fast. I was thinking of creating a simple review area where users can give stars for rating and type comments about the room. in addition, like / dislike was cancelled. we will define the room's popularity based on the star rating
